### ISSUE TITLE
Create a tool to load / extract information from a checkpoint.

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegatools#29]
Because people may need/want to see information which are available in a checkpoint, and because it might of any use for testing, we want to create  a command line tool which will allow us to read a checkpoint file.

This will need to be a subcommand which takes as input a checkpoint file, and extract data from it (e.g: load all proposals and print them on the commands line, loads all accounts and print them, etc).

# Tasks
- [ ] Add a new subcommand `vega checkpoint extract` (or similar)
- [ ] It can take as input a checkpoint file and:
  - [ ] Create the hash for this checkpoint file
  - [ ] Extract all accounts
  - [ ] Extract all proposals
  - [ ] Extract all network parameters
- [ ] Thins are displayed in an appropriate format which could be used for any automation / testing purpose (e.g: json).

**Comment by gordsport** [comment]
Issue moved from /vegaprotocol/vega#3779 to this repo
